In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.5


In [3]:
x=np.zeros(10)

In [4]:
x.itemsize*x.size


80

In [5]:
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:

x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
x=x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
x = np.arange(9).reshape(-1,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)


In [10]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
x = np.random.random((3,3,3))
print(x)

[[[0.89099465 0.73170244 0.04881272]
  [0.01319806 0.07833314 0.41382057]
  [0.77706475 0.94337608 0.87619322]]

 [[0.38034913 0.01382208 0.7277494 ]
  [0.51747835 0.30955781 0.01005532]
  [0.93219753 0.85297139 0.64348932]]

 [[0.2796319  0.66727641 0.32525872]
  [0.62712518 0.37407603 0.82166281]
  [0.52722975 0.71060257 0.04351836]]]


In [12]:
x = np.random.random((10,10))
print(x.min(), x.max())

0.008629812587694352 0.9989905469242338


In [13]:
x = np.random.random(30)
print(x.mean())

0.5973518822105178


In [14]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
x = np.zeros((10,10))
x[1:-1,1:-1] = 1
print(x)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1



False

In [17]:
x = np.diag(1+np.arange(4))
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [18]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
x = np.zeros((8,8));x[1::2,::2] = 1;x[::2,1::2] = 1
print(x)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
#copied didnt get the question
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


In [21]:
x=np.tile([[1,0],[0,1]],(4,4))
print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [22]:
x=np.random.random((5,5))
x=(x-np.mean(x))/np.std(x)

print(x)



[[-0.05699946  1.31263625  0.64008008  0.57713175  0.18464373]
 [ 1.35529837 -0.3964455  -1.339222    1.33404819 -1.62989336]
 [-1.13270615  0.2843633   1.41037992  1.29220127  0.24519837]
 [ 0.27297438 -0.88636279 -0.40160562 -1.32317589 -1.07341242]
 [-1.60191325  0.43109721  0.16877179  1.26868588 -0.93577406]]


In [23]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [24]:
x=np.random.random((5,3)) @ np.random.random((3,2))
print(x)

[[0.25428436 0.13083057]
 [0.75129602 0.75755608]
 [0.76451858 0.75322991]
 [0.75853716 0.36489389]
 [0.32921673 0.59064574]]


In [25]:
x=np.arange(10)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [27]:
Z=2
print(Z**Z)
#2 << Z >> 2
Z <- Z

1j*Z

Z/1/1
#Z<Z>Z

4


2.0

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [29]:
#copied
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 9.  6.  5.  7. -5. -4.  9.  4. -4.  5.]
[ 9.  6.  5.  7. -5. -4.  9.  4. -4.  5.]


In [30]:
x = np.random.randint(1,100,10)
y = np.random.randint(1,50,10)
print(x)
print(y)
print(np.intersect1d(x,y))

[21 56 32 43 53 12  9 82 14 99]
[ 3 40 13 10 22 44 14 10 40 42]
[14]


In [31]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:1114: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [33]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)

2021-09-08 2021-09-09 2021-09-10


In [34]:
x=np.arange('2016-07', '2016-08',dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [35]:
A=np.random.randint(0,10,5)
B=np.random.randint(0,10,5)

print(((A+B)*(-A/2)))


[-13.5 -40.  -27.    0.    0. ]


In [36]:
x = np.random.uniform(0,10,10)
print(x)
print(x - x%1)
print(x // 1)
print(np.floor(x))
print(np.trunc(x))

[7.14469169 7.58266166 9.08266792 5.79865759 0.79085966 7.35298856
 9.18460145 1.35653231 3.58368611 4.75203411]
[7. 7. 9. 5. 0. 7. 9. 1. 3. 4.]
[7. 7. 9. 5. 0. 7. 9. 1. 3. 4.]
[7. 7. 9. 5. 0. 7. 9. 1. 3. 4.]
[7. 7. 9. 5. 0. 7. 9. 1. 3. 4.]


In [37]:
x=np.tile(np.arange(5),(4,1))
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [38]:
def f():
  x=[]
  for i in range(10):
    x.append(i)
  return x
print(f())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [39]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [40]:
x=np.random.random(10)
x.sort()
print(x)

[0.06377743 0.18537598 0.23594244 0.24227378 0.47719022 0.50591512
 0.60881599 0.73278308 0.73819322 0.88086757]


In [41]:
x = np.arange(5)
np.add.reduce(x)


10

In [42]:
A=[1.0,2,3]
B=[1,2,3]
equal = np.array_equal(A,B)
print(equal)

True


In [43]:
x = np.arange(10)
x.flags.writeable = False

In [44]:
m = np.random.randint(1,10,(10,2))
x,y = m[:,0], m[:,1]
#print(m,x,y)
R = np.sqrt(x**2+y**2)
T = np.arctan2(y,x)
print(R)
print(T)

[ 3.16227766  7.61577311  6.08276253 12.72792206  9.8488578   6.70820393
  8.24621125  8.54400375  8.48528137  3.16227766]
[0.32175055 0.40489179 1.40564765 0.78539816 1.152572   0.46364761
 1.32581766 0.35877067 0.78539816 0.32175055]


In [45]:
x =np.random.randint(1,100,10)
x[x.argmax()] = 0
print(x)

[42 72 68  0 23  2 17 15 79 17]


In [46]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [47]:
x=np.arange(3)
y=np.arange(3)
z = 1/np.subtract.outer(x, x)
print(z)


[[ inf -1.  -0.5]
 [ 1.   inf -1. ]
 [ 0.5  1.   inf]]


In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [49]:
m = np.random.randint(1,10,(2,2))
print(m)

[[9 4]
 [2 4]]


In [50]:
import numpy as np
vec = np.arange(10)
sec = np.random.uniform(0,10)
index = (np.abs(vec-sec)).argmin()
print(vec[index])


4


In [51]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


In [52]:
v= np.random.random((100,2))
x,y = np.atleast_2d(v[:,0], v[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.34515433 0.88324303 ... 0.50882275 0.47285853 1.04058191]
 [0.34515433 0.         0.53808871 ... 0.17285696 0.45563562 0.69917239]
 [0.88324303 0.53808871 0.         ... 0.38480481 0.8112458  0.19537959]
 ...
 [0.50882275 0.17285696 0.38480481 ... 0.         0.58570329 0.56266963]
 [0.47285853 0.45563562 0.8112458  ... 0.58570329 0.         0.89116139]
 [1.04058191 0.69917239 0.19537959 ... 0.56266963 0.89116139 0.        ]]


In [53]:
from numpy  import *
v= np.random.uniform(1,10,10)
vint = array(v, dtype ='int32' )
print(v)
print(vint)


[6.15406451 2.94830107 2.19188416 9.22059298 4.49348622 2.86618988
 1.35639745 5.84766295 5.27688178 8.15742486]
[6 2 2 9 4 2 1 5 5 8]


In [54]:
#copied
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [55]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)
print("\n")
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [56]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(x**2+y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [57]:
m = 5; n = 3;
out = np.zeros((m,m),dtype=bool)
np.put(out,np.random.choice(range(m*m), n, replace=False),1)
print(out)

[[ True False False  True  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [58]:
x = np.random.random((3, 3))
x = x - x.mean(axis=1)
print(x)


[[-0.04517952  0.58774065 -0.16786207]
 [-0.51660141  0.00758569  0.09825694]
 [-0.12381573  0.44459077 -0.28471532]]


In [59]:
x = np.random.randint(0,10,(3,5))
print(x)
print(x[x[:,1].argsort()])

[[4 7 0 2 7]
 [4 2 4 8 0]
 [9 8 9 0 9]]
[[4 2 4 8 0]
 [4 7 0 2 7]
 [9 8 9 0 9]]


In [60]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

False


In [61]:
import numpy as np
x = np.random.uniform(0,1,10)
y = 0.5
m = x.flat[np.abs(x - y).argmin()]
print(m)

0.5025867388303541


In [62]:
import numpy as np
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
c=np.nditer([a,b,None])
for x,y,z in c: z[...] = x + y
print(c.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [63]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [64]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
x += np.bincount(y, minlength=len(x))
print(x)

[1. 5. 4. 1. 2. 2. 2. 4. 6. 3.]


In [65]:
X = [1,2,3,4,5,6]
I = [2,4,2,7,5,9]
F = np.bincount(I,X)
print(F)

[0. 0. 4. 0. 2. 5. 0. 4. 0. 6.]


In [66]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
col = np.unique(I.reshape(-1, 3), axis=0)
print(len(col))


64


In [67]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[52 44 71 52]
 [66 61 41 73]
 [59 61 46 49]]


In [68]:
import pandas as pd
D = np.random.uniform(0,1,10)
S = np.random.randint(0,10,10)
print(pd.Series(D).groupby(S).mean())



0    0.171282
1    0.502775
2    0.505826
4    0.200892
5    0.452843
8    0.472496
9    0.564916
dtype: float64


In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.12123082, 1.54296419, 1.47564571, 1.80611421, 1.77053765])

In [70]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [71]:
A = np.random.uniform(0,1,(5,5,3))
B = np.random.uniform(0,1,(5,5))
print(A * B[:,:,None])

[[[0.30648258 0.28975181 0.26432449]
  [0.0603525  0.04425402 0.01408382]
  [0.24726186 0.06575743 0.15449436]
  [0.08658913 0.05020901 0.04333455]
  [0.00242431 0.01922682 0.00416647]]

 [[0.22635004 0.73717365 0.21447961]
  [0.5565671  0.44828188 0.19016645]
  [0.57588993 0.82462134 0.8396357 ]
  [0.24345644 0.01928044 0.08738985]
  [0.04024452 0.021214   0.00536782]]

 [[0.04643305 0.09476982 0.05978375]
  [0.00296361 0.64160834 0.66071897]
  [0.06008836 0.0436228  0.02347232]
  [0.35822989 0.43955198 0.47826985]
  [0.86449175 0.51246798 0.23078384]]

 [[0.50468916 0.18385525 0.21185335]
  [0.21870181 0.18690277 0.42144196]
  [0.38326911 0.04080215 0.26343493]
  [0.46495593 0.17259533 0.80635185]
  [0.00394358 0.10980458 0.02171486]]

 [[0.0066057  0.0071798  0.00163892]
  [0.87580219 0.75046953 0.00954416]
  [0.13179882 0.38815158 0.44807459]
  [0.07324971 0.63282088 0.38214453]
  [0.71182606 0.76273476 0.87830771]]]


In [72]:
B = np.random.uniform(0,1,(5,5))
print(B)
B[[0,1]] = B[[1,0]]
print(B)

[[0.89307503 0.31186459 0.37771899 0.30932965 0.58267066]
 [0.5825975  0.38689206 0.14338128 0.05721116 0.42962557]
 [0.94426798 0.38739856 0.98503231 0.53460727 0.83530726]
 [0.24868993 0.01192524 0.49227723 0.62701524 0.40954172]
 [0.27717861 0.75421319 0.75349117 0.77420241 0.66187912]]
[[0.5825975  0.38689206 0.14338128 0.05721116 0.42962557]
 [0.89307503 0.31186459 0.37771899 0.30932965 0.58267066]
 [0.94426798 0.38739856 0.98503231 0.53460727 0.83530726]
 [0.24868993 0.01192524 0.49227723 0.62701524 0.40954172]
 [0.27717861 0.75421319 0.75349117 0.77420241 0.66187912]]


In [73]:
# copied I have no idea how to solve
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 18) ( 0, 76) ( 2, 28) ( 2, 45) ( 5, 59) ( 5, 88) ( 7, 38) ( 7, 74)
 (11, 71) (11, 81) (18, 76) (22, 42) (22, 57) (28, 45) (30, 67) (30, 82)
 (38, 74) (38, 81) (38, 95) (39, 42) (39, 43) (42, 43) (42, 57) (59, 88)
 (62, 77) (62, 80) (67, 82) (71, 81) (77, 80) (81, 95)]


In [74]:
C = np.bincount([1,2,3,4,4,6,7])
A = np.repeat(np.arange(len(C)),C)
print(A)






[1 2 3 4 4 6 7]


In [77]:
def mavg(a, n) :
    sum = np.cumsum(a)
    sum=np.cumsum(a, dtype=float)     # specifies type of output value(s)
    sum[n:] = sum[n:] - sum[:-n]
    return sum[n - 1:] / n
x = np.arange(20)
print(mavg(x, n=2))

[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5
 14.5 15.5 16.5 17.5 18.5]


In [79]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [80]:
Z = np.random.randint(0,2,10)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,10)
np.negative(Z, out=Z)

array([ 0.28366857,  0.86965356,  0.71622588, -0.71921844,  0.37066121,
        0.64974627,  0.8902217 ,  0.97497634, -0.69570579, -0.01181504])

In [81]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.30521791  6.42522055  3.74071762 13.46805373 17.28339977 11.60898401
  1.81306034  2.73535896  3.98494896  1.40675585]


In [82]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.74038805  0.22112106 11.43048605 10.27907914  2.17106489  2.93250439
   6.99812708  7.46875251  6.17648934 15.60963947]
 [ 0.91167926  5.34839313  6.00208288  4.74978063  1.26179033  2.85106021
   2.87543285  9.44033855  6.8302139  10.33366899]
 [ 4.28822891  3.34390055 14.27062831 10.79302267  1.15381762  2.40227948
   4.45808513  1.92530615  0.6810989  18.86683499]
 [10.93466878  6.15567777  2.99392732  3.79783768 14.96787829  9.5889371
  10.23580497  0.13296472  4.68599188  8.5551193 ]
 [ 9.61679336 12.55861974  2.35773155  5.61440683 10.52853352  1.45377609
   7.12419598  8.96986642  3.83167077  2.59472985]
 [ 0.08975518  5.17744977  5.99213606  4.25346627  2.31462624  1.75195743
   1.90796678  8.52187256  5.77824301 10.42553146]
 [10.54273681  6.86316754  2.45044478  3.82798765 14.1848378   8.41393562
   9.61510177  1.32308503  3.48667938  7.91758886]
 [ 3.9709553   6.13138355  5.91060621  6.53456822  2.72282438  7.09458568
   6.51378442 13.03525081 10.9092764   9.85258398]
 

In [83]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [84]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [85]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


In [86]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 3 3]
   [4 3 4]
   [1 4 1]]

  [[3 3 4]
   [3 4 3]
   [4 1 1]]

  [[3 4 2]
   [4 3 2]
   [1 1 2]]

  [[4 2 2]
   [3 2 2]
   [1 2 4]]

  [[2 2 3]
   [2 2 4]
   [2 4 2]]

  [[2 3 1]
   [2 4 3]
   [4 2 3]]

  [[3 1 1]
   [4 3 1]
   [2 3 1]]

  [[1 1 2]
   [3 1 0]
   [3 1 0]]]


 [[[4 3 4]
   [1 4 1]
   [4 3 3]]

  [[3 4 3]
   [4 1 1]
   [3 3 1]]

  [[4 3 2]
   [1 1 2]
   [3 1 2]]

  [[3 2 2]
   [1 2 4]
   [1 2 4]]

  [[2 2 4]
   [2 4 2]
   [2 4 0]]

  [[2 4 3]
   [4 2 3]
   [4 0 0]]

  [[4 3 1]
   [2 3 1]
   [0 0 2]]

  [[3 1 0]
   [3 1 0]
   [0 2 1]]]


 [[[1 4 1]
   [4 3 3]
   [4 4 4]]

  [[4 1 1]
   [3 3 1]
   [4 4 1]]

  [[1 1 2]
   [3 1 2]
   [4 1 4]]

  [[1 2 4]
   [1 2 4]
   [1 4 3]]

  [[2 4 2]
   [2 4 0]
   [4 3 1]]

  [[4 2 3]
   [4 0 0]
   [3 1 0]]

  [[2 3 1]
   [0 0 2]
   [1 0 3]]

  [[3 1 0]
   [0 2 1]
   [0 3 4]]]


 [[[4 3 3]
   [4 4 4]
   [0 3 3]]

  [[3 3 1]
   [4 4 1]
   [3 3 1]]

  [[3 1 2]
   [4 1 4]
   [3 1 0]]

  [[1 2 4]
   [1 4 3]
   [1 0 2]]

  [[2 4 0]
   

In [87]:
p, n = 5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


In [88]:
Z = np.ones((10,10))
k = 5
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print ('input array')
print (Z)
print ('block sum')
print (S)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[25. 25.]
 [25. 25.]]


In [89]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [90]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[97 96 98 99 95]


In [91]:
# 90

In [92]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')


In [93]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.72 s per loop
10 loops, best of 5: 144 ms per loop
10 loops, best of 5: 122 ms per loop


In [94]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 6 7]


In [95]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)


[[0 4 0]
 [1 1 2]
 [0 2 1]
 [2 4 4]
 [4 0 4]
 [4 3 1]
 [4 4 1]
 [1 3 3]
 [4 0 0]
 [1 1 0]]
[[0 4 0]
 [1 1 2]
 [0 2 1]
 [2 4 4]
 [4 0 4]
 [4 3 1]
 [4 4 1]
 [1 3 3]
 [4 0 0]
 [1 1 0]]


In [96]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [97]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 1 0]]


In [98]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)   

array([[2.60456374e-01, 5.29875465e-02, 2.70159606e-01, 2.99129094e-01,
        4.15501254e-01, 4.49033885e-01, 5.24174023e-01, 4.66510878e-01,
        4.47111836e-01, 5.43117789e-03],
       [6.24412065e-02, 1.27031114e-02, 6.47674368e-02, 7.17125144e-02,
        9.96113061e-02, 1.07650341e-01, 1.25664263e-01, 1.11840235e-01,
        1.07189554e-01, 1.30205798e-03],
       [3.01964167e-01, 6.14319400e-02, 3.13213761e-01, 3.46799989e-01,
        4.81717872e-01, 5.20594451e-01, 6.07709344e-01, 5.40856676e-01,
        5.18366094e-01, 6.29672096e-03],
       [4.11129411e-01, 8.36406436e-02, 4.26445927e-01, 4.72174154e-01,
        6.55867173e-01, 7.08798305e-01, 8.27406732e-01, 7.36385673e-01,
        7.05764359e-01, 8.57309395e-03],
       [2.25903320e-01, 4.59580331e-02, 2.34319287e-01, 2.59445581e-01,
        3.60379404e-01, 3.89463478e-01, 4.54635262e-01, 4.04621912e-01,
        3.87796415e-01, 4.71065882e-03],
       [1.57884398e-01, 3.21201848e-02, 1.63766338e-01, 1.81327168e-01,
   

In [99]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)              
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)     
y_int = np.interp(r_int, r, y)

In [100]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [101]:
X = np.random.randn(10) 
N = 100 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.57331255  0.48674526]
